import { ExerciseDetail } from "../types/exerciseDetail";

const mockExerciseDetails: Record<string, ExerciseDetail> = {
  "web-html-basics": {
    id: "web-html-basics",
    title: "タグを使い分けよう",
    category: "web",
    difficulty: "beginner",
    description: "HTMLの基本的なタグの使い分けを学びます。見出し、段落、リストなどの基本要素を正しく使えるようになることで、意味のある構造化された文書を作成できるようになります。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "タグを使い分けよう",
        type: "reading",
        description: "解説解説解説解説解説解説",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "インデントを整えよう",
        type: "reading",
        description: "座学座学座学座学座学座学",
        completed: false,
      },
      {
        id: "lesson-3",
        number: 3,
        title: "レイアウトの基礎を身につけよう",
        type: "practice",
        description: "",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-1",
      title: "確認テスト（選択式）",
      description: "これまで学んだ内容を確認しましょう",
      type: "choice",
      problem: `HTML文書で、リスト内のテキストを太字にするために適切なタグの組み合わせはどれですか？`,
      choices: ["<ul><li><b>テキスト</b></li></ul>", "<ol><p><strong>テキスト</strong></p></ol>", "<li><ul><em>テキスト</em></ul></li>", "<list><item><bold>テキスト</bold></item></list>"],
    },
  },
  "web-css-basics": {
    id: "web-css-basics",
    title: "CSSの基礎を学ぼう",
    category: "web",
    difficulty: "beginner",
    description: "CSSの基本的な記法とスタイリングを学びます。セレクタの使い方、色・フォントの設定、余白や境界線などをマスターして、美しいWebページを作れるようになります。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "セレクタの使い方",
        type: "reading",
        description: "CSSセレクタの基礎を学びます",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "色とフォントの設定",
        type: "practice",
        description: "色やフォントを変更してみましょう",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-2",
      title: "確認テスト（記述式）",
      description: "CSSの基礎を確認しましょう",
      type: "text",
      problem: `次のHTML要素にCSSを適用してください：

<div class="card">
  <h2 class="card-title">カードタイトル</h2>
</div>

要件：.card-titleクラスに、文字色を濃い青色（#1E40AF）、フォントサイズを24pxに設定するCSSを記述してください。`,
      placeholder: "CSSコードをここに記述してください（例: .card-title { color: #1E40AF; ... }）...",
    },
  },
  "web-responsive-design": {
    id: "web-responsive-design",
    title: "レスポンシブデザイン入門",
    category: "web",
    difficulty: "beginner",
    description: "モバイルフレンドリーなWebサイトの作り方を学びます。メディアクエリやFlexboxを使って、様々な画面サイズに対応したレイアウトを作成できるようになります。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "メディアクエリの基本",
        type: "reading",
        description: "画面サイズに応じたスタイル変更を学びます",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "Flexboxでレイアウト",
        type: "practice",
        description: "柔軟なレイアウトを作成しましょう",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-3",
      title: "確認テスト（選択式）",
      description: "レスポンシブデザインの理解を確認しましょう",
      type: "choice",
      problem: `レスポンシブデザインで、画面幅768px以下の場合に背景色を変更したい場合、どのメディアクエリを使用しますか？`,
      choices: ["@media (max-width: 768px) { ... }", "@media (min-width: 768px) { ... }", "@media screen and (width: 768px) { ... }", "@media only (max-height: 768px) { ... }"],
    },
  },
  "web-javascript-basics": {
    id: "web-javascript-basics",
    title: "JavaScript基礎",
    category: "web",
    difficulty: "intermediate",
    description: "JavaScriptの基本文法とDOM操作を学びます。変数、データ型、関数などの基礎を理解し、ブラウザ上でHTMLを動的に操作できるようになります。Webアプリケーション開発の第一歩です。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "変数とデータ型",
        type: "reading",
        description: "JavaScriptの変数宣言とデータ型について学びます",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "関数の基礎",
        type: "reading",
        description: "関数の定義と呼び出し方を学びます",
        completed: false,
      },
      {
        id: "lesson-3",
        number: 3,
        title: "DOM操作の基本",
        type: "reading",
        description: "HTMLをJavaScriptで操作する方法を学びます",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-4",
      title: "確認テスト（選択式）",
      description: "JavaScriptの基礎知識を確認しましょう",
      type: "choice",
      problem: `以下のコードの実行結果として正しいものを選んでください：

\`\`\`javascript
let x = 5;
const y = 10;
x = x + y;
console.log(x);
\`\`\`

このコードを実行すると、コンソールに何が表示されますか？`,
      choices: [
        "5（xの初期値）",
        "10（yの値）",
        "15（xとyの合計）",
        "エラーが発生する（constは変更できないため）",
      ],
    },
  },
  "ai-machine-learning-basics": {
    id: "ai-machine-learning-basics",
    title: "機械学習の基礎",
    category: "ai",
    difficulty: "beginner",
    description: "機械学習の基本概念と用語を学びます。教師あり学習、教師なし学習、過学習などの重要な概念を理解し、AIエンジニアリングの基礎を身につけます。データサイエンスへの第一歩です。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "機械学習とは",
        type: "reading",
        description: "機械学習の定義と種類について学びます",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "教師あり学習と教師なし学習",
        type: "reading",
        description: "学習方法の違いを理解します",
        completed: false,
      },
      {
        id: "lesson-3",
        number: 3,
        title: "過学習と汎化",
        type: "reading",
        description: "モデルの性能評価について学びます",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-5",
      title: "確認テスト（選択式）",
      description: "機械学習の基礎概念を確認しましょう",
      type: "choice",
      problem: `教師あり学習の説明として、最も適切なものを選んでください：`,
      choices: [
        "正解ラベル付きのデータを使って学習し、未知のデータに対して予測を行う手法",
        "正解ラベルなしのデータからパターンや構造を発見する手法",
        "報酬を最大化するように行動を学習する手法",
        "人間が全ての判断を行い、機械は補助的な役割のみ果たす手法",
      ],
    },
  },
  "security-web-security-basics": {
    id: "security-web-security-basics",
    title: "Webセキュリティ基礎",
    category: "security",
    difficulty: "intermediate",
    description: "Webアプリケーションの基本的な脆弱性と対策を学びます。XSS、SQLインジェクション、認証/セッション管理などの重要なセキュリティ概念を理解し、安全なWebアプリケーションを開発できるようになります。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "XSS（クロスサイトスクリプティング）",
        type: "reading",
        description: "XSS攻撃の仕組みと対策を学びます",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "SQLインジェクション",
        type: "reading",
        description: "SQLインジェクションの危険性と防御方法を学びます",
        completed: false,
      },
      {
        id: "lesson-3",
        number: 3,
        title: "認証とセッション管理",
        type: "reading",
        description: "安全な認証方法とセッション管理について学びます",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-6",
      title: "確認テスト（選択式）",
      description: "Webセキュリティの基礎知識を確認しましょう",
      type: "choice",
      problem: `次のPythonコードにSQLインジェクションの脆弱性があります。この脆弱性を防ぐための最も適切な対策はどれですか？

\`\`\`python
username = request.GET['username']
query = "SELECT * FROM users WHERE username = '" + username + "'"
cursor.execute(query)
\`\`\``,
      choices: ["プリペアドステートメント（パラメータ化されたクエリ）を使用する", "usernameをエスケープ処理してから文字列結合する", "クエリ全体をHTMLエンコードする", "usernameの長さを制限して10文字以内にする"],
    },
  },
  "web-react-intro": {
    id: "web-react-intro",
    title: "React入門",
    category: "web",
    difficulty: "intermediate",
    description: "Reactコンポーネントの作成方法を学びます。StateとPropsの使い方、イベント処理の基本をマスターしましょう。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Reactコンポーネント基礎",
        type: "reading",
        description: "Reactコンポーネントの基本構造を理解します",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "Stateの管理",
        type: "practice",
        description: "useStateフックを使った状態管理",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-react-1",
      title: "確認テスト",
      description: "カウンターコンポーネントを作成してください",
      type: "text",
      problem: `useStateを使ってカウンター機能を実装してください。「+」ボタンでカウントが1増える、「-」ボタンで1減る、「リセット」ボタンで0に戻る機能を持つReactコンポーネントのコードを記述してください。`,
      placeholder: "const Counter = () => { const [count, setCount] = useState(0); ... }の形式でコードを記述してください...",
    },
  },
  "web-nextjs-app": {
    id: "web-nextjs-app",
    title: "Next.jsでアプリ開発",
    category: "web",
    difficulty: "advanced",
    description: "Next.jsを使ったフルスタックアプリケーション開発を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Next.jsプロジェクト構成",
        type: "reading",
        description: "App Routerの基礎",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-nextjs-1",
      title: "確認テスト",
      description: "Next.jsの基本を確認しましょう",
      type: "text",
      problem: `Next.jsのApp Routerにおいて、page.tsxとlayout.tsxはそれぞれどのような役割を持っていますか？両者の違いと使い分けについて説明してください。`,
      placeholder: "page.tsxとlayout.tsxの役割と違いを説明してください...",
    },
  },
  "ai-1": {
    id: "ai-1",
    title: "機械学習の基礎",
    category: "ai",
    difficulty: "beginner",
    description: "機械学習の基本概念と手法を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "機械学習とは",
        type: "reading",
        description: "教師あり学習と教師なし学習",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-ai-1",
      title: "確認テスト",
      description: "機械学習の基礎知識を確認します",
      type: "choice",
      problem: `機械学習における「教師あり学習」の説明として最も適切なものはどれですか？`,
      choices: ["正解ラベル付きのデータを使って、入力と出力の関係を学習する手法", "正解ラベルなしでデータのパターンや構造を発見する手法", "報酬を最大化するように行動を学習する手法", "複数のモデルを組み合わせて予測精度を向上させる手法"],
    },
  },
  "ai-2": {
    id: "ai-2",
    title: "Python for AI",
    category: "ai",
    difficulty: "beginner",
    description: "AI開発に必要なPythonの基礎を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "NumPy入門",
        type: "practice",
        description: "配列操作の基礎",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-ai-2",
      title: "確認テスト",
      description: "NumPyの基本操作",
      type: "text",
      problem: `NumPyを使って、1から10までの整数を含む配列を作成し、その全要素を2倍にして平均値を計算するコードを記述してください。`,
      placeholder: "import numpy as np\narr = np.arange(...)\n... の形式でコードを記述してください...",
    },
  },
  "game-1": {
    id: "game-1",
    title: "Unity基礎",
    category: "game",
    difficulty: "beginner",
    description: "Unityエンジンの基本操作を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Unity画面構成",
        type: "reading",
        description: "Scene、Game、Hierarchyビューの使い方",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-game-1",
      title: "確認テスト",
      description: "Unityの基本を確認します",
      type: "choice",
      problem: `UnityエディタでゲームオブジェクトのTransform（位置、回転、スケール）やアタッチされたコンポーネントのプロパティを編集できるビューはどれですか？`,
      choices: ["Inspectorビュー", "Sceneビュー", "Hierarchyビュー", "Projectビュー"],
    },
  },
  "game-2": {
    id: "game-2",
    title: "C#ゲームプログラミング",
    category: "game",
    difficulty: "beginner",
    description: "UnityでのC#スクリプティングを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "MonoBehaviour基礎",
        type: "practice",
        description: "Start()とUpdate()の使い方",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-game-2",
      title: "確認テスト",
      description: "キューブを動かすスクリプトを作成",
      type: "text",
      problem: `UnityでGameObjectを矢印キーで上下左右に移動させるC#スクリプトを作成してください。Input.GetAxis()とtransform.Translate()を使用し、移動速度を変数で調整できるようにしてください。`,
      placeholder: "public class PlayerController : MonoBehaviour { public float speed = 5f; ... } の形式でコードを記述してください...",
    },
  },
  "infrastructure-1": {
    id: "infrastructure-1",
    title: "Docker基礎",
    category: "infrastructure",
    difficulty: "beginner",
    description: "コンテナ技術の基礎を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Dockerとは",
        type: "reading",
        description: "コンテナとイメージの概念",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-infra-1",
      title: "確認テスト",
      description: "Dockerfileを作成してください",
      type: "text",
      problem: `Node.js 20を使用し、package.jsonをコピーしてnpm installを実行、アプリケーションコードをコピーしてポート3000を公開、npm startで起動するDockerfileを記述してください。`,
      placeholder: "FROM node:20\nWORKDIR /app\nCOPY package*.json ./\n... の形式でDockerfileを記述してください...",
    },
  },
  "infrastructure-2": {
    id: "infrastructure-2",
    title: "Kubernetes入門",
    category: "infrastructure",
    difficulty: "intermediate",
    description: "コンテナオーケストレーションを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Kubernetesの概念",
        type: "reading",
        description: "Pod、Service、Deploymentの役割",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-infra-2",
      title: "確認テスト",
      description: "Kubernetesの基本を確認",
      type: "choice",
      problem: `Kubernetesにおいて、1つ以上のコンテナをまとめた最小のデプロイ単位で、同じIPアドレスとストレージを共有するリソースは何ですか？`,
      choices: ["Pod", "Service", "Deployment", "ReplicaSet"],
    },
  },
  "design-1": {
    id: "design-1",
    title: "UI/UX基礎",
    category: "design",
    difficulty: "beginner",
    description: "ユーザーインターフェース設計の原則を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "UIデザインの原則",
        type: "reading",
        description: "一貫性、フィードバック、制約",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-design-1",
      title: "確認テスト",
      description: "UIデザインの原則",
      type: "choice",
      problem: `UIデザインの原則の一つで、「UI全体で似た要素は似た見た目と振る舞いを持つようにし、ユーザーの学習コストを下げる」ことを指すのはどれですか？`,
      choices: ["一貫性（Consistency）", "フィードバック（Feedback）", "可視性（Visibility）", "制約（Constraints）"],
    },
  },
  "design-2": {
    id: "design-2",
    title: "Figma実践",
    category: "design",
    difficulty: "beginner",
    description: "Figmaでのデザイン制作を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Figmaの基本操作",
        type: "practice",
        description: "フレーム、シェイプ、テキストの作成",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-design-2",
      title: "確認テスト",
      description: "簡単なボタンをデザイン",
      type: "text",
      problem: `Figmaでボタンコンポーネントを作成する際、角丸の長方形を作成し、その上にテキストラベルを配置し、ホバー状態のバリエーションを作成してコンポーネント化する手順を説明してください。`,
      placeholder: "1. 長方形ツールで角丸を設定... 2. テキストを中央配置... 3. バリエーションを... のように手順を記述してください...",
    },
  },
  "security-1": {
    id: "security-1",
    title: "セキュリティ基礎",
    category: "security",
    difficulty: "beginner",
    description: "情報セキュリティの基本を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "セキュリティの3要素",
        type: "reading",
        description: "機密性、完全性、可用性",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-security-1",
      title: "確認テスト",
      description: "セキュリティの基礎知識",
      type: "choice",
      problem: `情報セキュリティの3要素（CIA）の中で、「認可されたユーザーのみが情報にアクセスできること」を指すのはどれですか？`,
      choices: ["機密性（Confidentiality）", "完全性（Integrity）", "可用性（Availability）", "冗長性（Redundancy）"],
    },
  },
  "security-2": {
    id: "security-2",
    title: "Webセキュリティ",
    category: "security",
    difficulty: "intermediate",
    description: "XSSやCSRFなどの脆弱性対策を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "XSS対策",
        type: "practice",
        description: "クロスサイトスクリプティングの防止",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-security-2",
      title: "確認テスト",
      description: "XSSとCSRFの対策",
      type: "choice",
      problem: `XSS（クロスサイトスクリプティング）攻撃を防ぐための最も基本的な対策はどれですか？`,
      choices: ["ユーザー入力をHTML出力する前にエスケープ（サニタイズ）する", "CSRFトークンを使用する", "HTTPSを使用する", "SQLインジェクション対策を行う"],
    },
  },
  "web-6": {
    id: "web-6",
    title: "パフォーマンス最適化",
    category: "web",
    difficulty: "expert",
    description: "Webアプリケーションのパフォーマンス改善手法を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "ローディング最適化",
        type: "reading",
        description: "画像の遅延読み込み、コード分割",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "レンダリング最適化",
        type: "practice",
        description: "再レンダリングの削減テクニック",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-performance",
      title: "確認テスト",
      description: "パフォーマンス最適化の知識",
      type: "choice",
      problem: `Webサイトのパフォーマンスを改善する手法として、最も効果的なものはどれですか？`,
      choices: [
        "すべての画像をBase64エンコードしてHTMLに埋め込む",
        "画像の遅延読み込み（Lazy Loading）を実装する",
        "すべてのCSSを1つの巨大なファイルにまとめる",
        "JavaScriptを同期的に読み込む",
      ],
    },
  },
  "web-7": {
    id: "web-7",
    title: "TypeScript基礎",
    category: "web",
    difficulty: "intermediate",
    description: "TypeScriptの型システムと基本文法を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "型の基礎",
        type: "reading",
        description: "プリミティブ型、配列、オブジェクト型",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "インターフェースと型エイリアス",
        type: "practice",
        description: "複雑な型の定義",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-typescript",
      title: "確認テスト",
      description: "TypeScriptの型定義",
      type: "text",
      problem: `User型を定義してください。Userは以下のプロパティを持ちます：
- id: number型
- name: string型
- email: string型（オプショナル）

【記述例】
interface User { ... }`,
      placeholder: "interface User { id: number; name: string; email?: string; }",
    },
  },
  "web-8": {
    id: "web-8",
    title: "Tailwind CSS実践",
    category: "web",
    difficulty: "beginner",
    description: "ユーティリティファーストCSSフレームワークを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Tailwindの基本クラス",
        type: "reading",
        description: "余白、色、フォントのユーティリティクラス",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "レスポンシブ対応",
        type: "practice",
        description: "sm:, md:, lg:プレフィックスの使い方",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-tailwind",
      title: "確認テスト",
      description: "Tailwind CSSの実装",
      type: "choice",
      problem: `Tailwind CSSで、青い背景・白い文字・パディング16px・角丸のボタンを作成する場合、正しいクラス指定はどれですか？`,
      choices: [
        "<button class='background-blue color-white padding-16 border-radius'>ボタン</button>",
        "<button class='bg-blue-500 text-white p-4 rounded-lg'>ボタン</button>",
        "<button class='blue white padding-4 round-lg'>ボタン</button>",
        "<button class='bg:blue text:white pad:4 border:round'>ボタン</button>",
      ],
    },
  },
  "web-9": {
    id: "web-9",
    title: "REST API設計",
    category: "web",
    difficulty: "intermediate",
    description: "RESTfulなAPI設計の原則を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "RESTの原則",
        type: "reading",
        description: "リソース指向、HTTPメソッドの使い分け",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "エンドポイント設計",
        type: "practice",
        description: "適切なURL設計",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-rest-api",
      title: "確認テスト",
      description: "REST API設計の知識",
      type: "choice",
      problem: `RESTful APIで、ID=123の記事を取得するエンドポイントとして最も適切なものはどれですか？`,
      choices: [
        "GET /getArticle?id=123",
        "GET /articles/123",
        "POST /articles/get/123",
        "FETCH /article-123",
      ],
    },
  },
  "web-10": {
    id: "web-10",
    title: "Git/GitHub実践",
    category: "web",
    difficulty: "beginner",
    description: "バージョン管理とチーム開発を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Gitの基本コマンド",
        type: "reading",
        description: "add, commit, push, pull",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "ブランチ戦略",
        type: "practice",
        description: "featureブランチとPull Request",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-git",
      title: "確認テスト",
      description: "Git/GitHubの操作",
      type: "choice",
      problem: `新しいブランチ"feature-login"を作成して切り替えるコマンドはどれですか？`,
      choices: [
        "git branch feature-login",
        "git checkout -b feature-login",
        "git create branch feature-login",
        "git new-branch feature-login",
      ],
    },
  },
  "web-11": {
    id: "web-11",
    title: "Webアクセシビリティ",
    category: "web",
    difficulty: "intermediate",
    description: "誰でも使いやすいWebサイトの作り方を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "セマンティックHTML",
        type: "reading",
        description: "意味のあるタグの使用",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "ARIA属性",
        type: "practice",
        description: "スクリーンリーダー対応",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-accessibility",
      title: "確認テスト",
      description: "アクセシビリティの実装",
      type: "choice",
      problem: `スクリーンリーダーユーザーのために、アイコンのみのボタンに説明を追加する最も適切な方法はどれですか？`,
      choices: [
        "<button title='閉じる'><img src='close.png'></button>",
        "<button aria-label='閉じる'><img src='close.png' alt=''></button>",
        "<button><img src='close.png' alt='閉じる'></button>",
        "<button class='close-button'><img src='close.png'></button>",
      ],
    },
  },
  "web-12": {
    id: "web-12",
    title: "PWA開発",
    category: "web",
    difficulty: "advanced",
    description: "Progressive Web Appの構築を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Service Workerの基礎",
        type: "reading",
        description: "オフライン対応の仕組み",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "マニフェストファイル",
        type: "practice",
        description: "アプリのメタデータ設定",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-pwa",
      title: "確認テスト",
      description: "PWAの知識",
      type: "text",
      problem: `PWA（Progressive Web App）が提供する「Connectivity independent（接続非依存）」とはどのような特徴ですか？Service Workerやキャッシュの仕組みと関連付けて説明してください。`,
      placeholder: "オフラインでも動作する仕組みやService Workerの役割を説明してください...",
    },
  },
  "ai-3": {
    id: "ai-3",
    title: "ニューラルネットワーク入門",
    category: "ai",
    difficulty: "intermediate",
    description: "ニューラルネットワークの仕組みを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "パーセプトロンの基礎",
        type: "reading",
        description: "最も単純なニューラルネットワーク",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "多層ニューラルネットワーク",
        type: "practice",
        description: "隠れ層を持つネットワーク",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-ai-3",
      title: "確認テスト",
      description: "ニューラルネットワークの理解",
      type: "choice",
      problem: `ニューラルネットワークにおいて、非線形性を導入し、複雑なパターンを学習可能にする役割を持つものは何ですか？`,
      choices: [
        "バイアス項",
        "活性化関数",
        "学習率",
        "バッチサイズ",
      ],
    },
  },
  "ai-4": {
    id: "ai-4",
    title: "ディープラーニング実践",
    category: "ai",
    difficulty: "expert",
    description: "CNNとRNNの実装を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "CNN（畳み込みニューラルネットワーク）",
        type: "reading",
        description: "画像認識に使われるネットワーク",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "RNN（再帰型ニューラルネットワーク）",
        type: "practice",
        description: "時系列データ処理",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-ai-4",
      title: "確認テスト",
      description: "ディープラーニングの知識",
      type: "choice",
      problem: `CNN（畳み込みニューラルネットワーク）が主に使われるタスクはどれですか？`,
      choices: ["画像認識や物体検出", "時系列データの予測", "自然言語処理の文章生成", "強化学習のゲームAI"],
    },
  },
  "ai-5": {
    id: "ai-5",
    title: "データ前処理",
    category: "ai",
    difficulty: "beginner",
    description: "データクリーニングと正規化を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "欠損値の処理",
        type: "reading",
        description: "NaNデータの扱い方",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "正規化とスケーリング",
        type: "practice",
        description: "データの範囲調整",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-ai-5",
      title: "確認テスト",
      description: "データ前処理の手法",
      type: "text",
      problem: `機械学習でデータの欠損値（NaN）を処理する際の主な手法を3つ挙げ、それぞれの特徴と使い分けを説明してください。`,
      placeholder: "例：削除、平均値補完、予測モデルによる補完などを説明してください...",
    },
  },
  "ai-6": {
    id: "ai-6",
    title: "自然言語処理入門",
    category: "ai",
    difficulty: "beginner",
    description: "テキストデータの処理手法を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "トークン化",
        type: "reading",
        description: "テキストの分割処理",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "TF-IDF",
        type: "practice",
        description: "単語の重要度計算",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-ai-6",
      title: "確認テスト",
      description: "自然言語処理の基礎",
      type: "choice",
      problem: `自然言語処理（NLP）で、「テキストを単語やトークンに分割する処理」を何と言いますか？`,
      choices: ["トークン化（Tokenization）", "ステミング（Stemming）", "レンマ化（Lemmatization）", "ベクトル化（Vectorization）"],
    },
  },
  "ai-7": {
    id: "ai-7",
    title: "コンピュータビジョン",
    category: "ai",
    difficulty: "advanced",
    description: "画像認識と物体検出を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "画像認識",
        type: "reading",
        description: "CNNによる画像分類",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "物体検出",
        type: "practice",
        description: "YOLOやR-CNNの仕組み",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-ai-7",
      title: "確認テスト",
      description: "コンピュータビジョンの知識",
      type: "text",
      problem: `画像認識（Image Classification）と物体検出（Object Detection）の違いを説明し、それぞれの出力形式と具体的な利用例を挙げてください。`,
      placeholder: "画像認識は1枚の画像に1つのラベルを、物体検出は...のように説明してください...",
    },
  },
  "ai-8": {
    id: "ai-8",
    title: "強化学習基礎",
    category: "ai",
    difficulty: "advanced",
    description: "Q学習とDQNの実装を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "強化学習の基本概念",
        type: "reading",
        description: "エージェント、環境、報酬",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "Q学習",
        type: "practice",
        description: "Q値の更新アルゴリズム",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-ai-8",
      title: "確認テスト",
      description: "強化学習の理解",
      type: "text",
      problem: `強化学習における「報酬（Reward）」と「方策（Policy）」の関係を説明してください。エージェントがどのように報酬を最大化するための方策を学習するか説明してください。`,
      placeholder: "報酬はエージェントの行動の評価で、方策は...のように説明してください...",
    },
  },
  "ai-9": {
    id: "ai-9",
    title: "TensorFlow実践",
    category: "ai",
    difficulty: "intermediate",
    description: "TensorFlowでのモデル構築を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "TensorFlowの基礎",
        type: "reading",
        description: "テンソルと演算",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "Kerasでモデル構築",
        type: "practice",
        description: "Sequentialモデルの作成",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-ai-9",
      title: "確認テスト",
      description: "TensorFlowの知識",
      type: "text",
      problem: `Kerasでシンプルなニューラルネットワークを構築する際の基本的な流れを説明してください。Sequential()を使ったモデル定義からコンパイル、学習までのステップを記述してください。`,
      placeholder: "1. tf.keras.Sequential()でモデル定義 2. add()でレイヤー追加 3. compile()で...のように記述してください...",
    },
  },
  "ai-10": {
    id: "ai-10",
    title: "PyTorch実装",
    category: "ai",
    difficulty: "advanced",
    description: "PyTorchでのディープラーニング実装を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "PyTorchの基本",
        type: "reading",
        description: "テンソル操作と自動微分",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "nn.Moduleでモデル定義",
        type: "practice",
        description: "カスタムモデルの作成",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-ai-10",
      title: "確認テスト",
      description: "PyTorchの基礎",
      type: "text",
      problem: `PyTorchの特徴的な実行方式である「動的計算グラフ（Define-by-Run）」について説明し、TensorFlowの静的計算グラフとどう違うのか比較してください。`,
      placeholder: "PyTorchは実行時に計算グラフを構築し...、一方TensorFlowは...のように説明してください...",
    },
  },
  "ai-11": {
    id: "ai-11",
    title: "MLOps実践",
    category: "ai",
    difficulty: "expert",
    description: "機械学習モデルのデプロイと運用を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "ML実験管理",
        type: "reading",
        description: "MLflowの使い方",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "モデルのデプロイ",
        type: "practice",
        description: "API化と監視",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-ai-11",
      title: "確認テスト",
      description: "MLOpsの知識",
      type: "text",
      problem: `MLOps（機械学習運用）における「実験管理（Experiment Tracking）」の重要性と、MLflowなどのツールを使って何を記録・管理すべきか説明してください。`,
      placeholder: "ハイパーパラメータ、メトリクス、モデルのバージョン管理...など説明してください...",
    },
  },
  "security-3": {
    id: "security-3",
    title: "ペネトレーションテスト",
    category: "security",
    difficulty: "advanced",
    description: "ペンテストの手法と実施方法を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "ペンテストの基礎",
        type: "reading",
        description: "侵入テストの手法と倫理",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "脆弱性スキャン",
        type: "practice",
        description: "ツールを使った診断",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-security-3",
      title: "確認テスト",
      description: "ペンテストの知識",
      type: "choice",
      problem: `ペネトレーションテスト（侵入テスト）において、攻撃者の視点から情報収集を行う最初の段階を何と言いますか？`,
      choices: ["偵察（Reconnaissance）", "スキャニング（Scanning）", "侵入（Exploitation）", "報告（Reporting）"],
    },
  },
  "security-4": {
    id: "security-4",
    title: "暗号化技術",
    category: "security",
    difficulty: "intermediate",
    description: "対称暗号と公開鍵暗号を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "対称鍵暗号",
        type: "reading",
        description: "AES、DESなどの暗号方式",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "公開鍵暗号",
        type: "practice",
        description: "RSA暗号の仕組み",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-security-4",
      title: "確認テスト",
      description: "暗号化技術の理解",
      type: "choice",
      problem: `対称鍵暗号と公開鍵暗号の主な違いとして正しいのはどれですか？`,
      choices: ["対称鍵暗号は暗号化と復号化に同じ鍵を使い、公開鍵暗号は異なる鍵を使う", "対称鍵暗号は遅く、公開鍵暗号は速い", "対称鍵暗号は安全で、公開鍵暗号は危険", "対称鍵暗号は新しく、公開鍵暗号は古い技術"],
    },
  },
  "security-5": {
    id: "security-5",
    title: "OAuth/JWT認証",
    category: "security",
    difficulty: "intermediate",
    description: "モダン認証の実装を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "OAuthの仕組み",
        type: "reading",
        description: "OAuth 2.0フロー",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "JWTの構造",
        type: "practice",
        description: "トークンベース認証",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-security-5",
      title: "確認テスト",
      description: "OAuth/JWTの知識",
      type: "text",
      problem: `JWT（JSON Web Token）の構造について説明してください。Header、Payload、Signatureの3つの部分がそれぞれどのような情報を含み、どのような役割を持つか記述してください。`,
      placeholder: "Headerはアルゴリズム情報を、Payloadはユーザー情報を、Signatureは...のように説明してください...",
    },
  },
  "security-6": {
    id: "security-6",
    title: "OWASP Top 10",
    category: "security",
    difficulty: "beginner",
    description: "代表的なWebアプリケーション脆弱性を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "インジェクション攻撃",
        type: "reading",
        description: "SQLインジェクションの仕組み",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "認証の不備",
        type: "practice",
        description: "セッション管理の脆弱性",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-security-6",
      title: "確認テスト",
      description: "OWASP Top 10の知識",
      type: "text",
      problem: `OWASP Top 10から任意の脆弱性を1つ選び、その脆弱性の概要、攻撃例、対策方法を具体的に説明してください。`,
      placeholder: "例：SQLインジェクションの場合、概要は...、攻撃例は...、対策は...のように説明してください...",
    },
  },
  "security-7": {
    id: "security-7",
    title: "セキュアコーディング",
    category: "security",
    difficulty: "intermediate",
    description: "安全なコードの書き方を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "入力バリデーション",
        type: "reading",
        description: "データ検証の重要性",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "エラーハンドリング",
        type: "practice",
        description: "安全なエラー処理",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-security-7",
      title: "確認テスト",
      description: "セキュアコーディングの実践",
      type: "text",
      problem: `セキュアコーディングにおいて「入力検証（Input Validation）」が重要視されています。この原則を適用する際の具体的な実装方法と注意点を説明してください。`,
      placeholder: "ホワイトリスト方式の使用、型チェック、長さ制限...などの具体的な手法を説明してください...",
    },
  },
  "security-8": {
    id: "security-8",
    title: "ネットワークセキュリティ",
    category: "security",
    difficulty: "advanced",
    description: "ファイアウォールとIDS/IPSを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "ファイアウォールの設定",
        type: "reading",
        description: "パケットフィルタリング",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "IDS/IPSの運用",
        type: "practice",
        description: "IDS/IPSの運用",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-security-8",
      title: "確認テスト",
      description: "ネットワークセキュリティの知識",
      type: "choice",
      problem: `IDS（侵入検知システム）とIPS（侵入防止システム）の最も大きな違いは何ですか？`,
      choices: ["IDSは検知のみ、IPSは検知と防御を行う", "IDSは高価で、IPSは安価", "IDSは古く、IPSは新しい技術", "IDSはソフトウェア、IPSはハードウェア"],
    },
  },
  "security-9": {
    id: "security-9",
    title: "インシデント対応",
    category: "security",
    difficulty: "advanced",
    description: "セキュリティ事故への対処を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "インシデントレスポンスプロセス",
        type: "reading",
        description: "対応の6段階",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "フォレンジック調査",
        type: "practice",
        description: "証拠の収集と分析",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-security-9",
      title: "確認テスト",
      description: "インシデント対応の知識",
      type: "text",
      problem: `セキュリティインシデント対応の6段階のうち、「封じ込め（Containment）」フェーズで行う具体的な対応内容と、その際に注意すべき点を説明してください。`,
      placeholder: "感染したシステムの隔離、ネットワークの遮断...などの対応と、証拠保全の重要性...などを説明してください...",
    },
  },
  "security-10": {
    id: "security-10",
    title: "クラウドセキュリティ",
    category: "security",
    difficulty: "advanced",
    description: "AWS/Azureのセキュリティ対策を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "IAMの管理",
        type: "reading",
        description: "アクセス制御の設計",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "データ保護",
        type: "practice",
        description: "暗号化とバックアップ",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-security-10",
      title: "確認テスト",
      description: "クラウドセキュリティの知識",
      type: "text",
      problem: `クラウドセキュリティにおいて「最小権限の原則（Principle of Least Privilege）」をIAM（Identity and Access Management）でどのように実装するか説明してください。`,
      placeholder: "必要最小限の権限のみを付与、ロールベースのアクセス制御...など説明してください...",
    },
  },
  "infrastructure-3": {
    id: "infrastructure-3",
    title: "CI/CD構築",
    category: "infrastructure",
    difficulty: "advanced",
    description: "GitHub Actionsでの自動化を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "CI/CDの概念",
        type: "reading",
        description: "継続的インテグレーション・デリバリー",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "GitHub Actionsの設定",
        type: "practice",
        description: "ワークフローの作成",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-infrastructure-3",
      title: "確認テスト",
      description: "CI/CDの知識",
      type: "text",
      problem: `CI/CDパイプラインにおける「テスト（Test）」ステージで実行すべきテストの種類と、それぞれの目的を説明してください。`,
      placeholder: "ユニットテスト、統合テスト、E2Eテストなどの種類と、品質保証の観点から説明してください...",
    },
  },
  "infrastructure-4": {
    id: "infrastructure-4",
    title: "AWS基礎",
    category: "infrastructure",
    difficulty: "beginner",
    description: "EC2, S3, RDSの基本を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "EC2インスタンス",
        type: "reading",
        description: "仮想サーバーの構築",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "S3ストレージ",
        type: "practice",
        description: "オブジェクトストレージの利用",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-infrastructure-4",
      title: "確認テスト",
      description: "AWSサービスの理解",
      type: "choice",
      problem: `AWSで静的ファイル（画像、動画、HTMLなど）をインターネットに公開する際に最も適したストレージサービスはどれですか？`,
      choices: ["S3（Simple Storage Service）", "EC2（Elastic Compute Cloud）", "RDS（Relational Database Service）", "Lambda"],
    },
  },
  "infrastructure-5": {
    id: "infrastructure-5",
    title: "Terraform実践",
    category: "infrastructure",
    difficulty: "advanced",
    description: "Infrastructure as Codeを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Terraformの基礎",
        type: "reading",
        description: "HCL記法とリソース定義",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "Terraformの実践",
        type: "practice",
        description: "AWSリソースの構築",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-infrastructure-5",
      title: "確認テスト",
      description: "Terraformの知識",
      type: "text",
      problem: `Terraformの「State（状態）」とは何か、なぜ重要なのか、どのように管理すべきかを説明してください。`,
      placeholder: "Stateは現在のインフラ状態を記録し...、team開発では...のように説明してください...",
    },
  },
  "infrastructure-6": {
    id: "infrastructure-6",
    title: "Linuxサーバー管理",
    category: "infrastructure",
    difficulty: "intermediate",
    description: "シェルコマンドとシステム管理を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "基本コマンド",
        type: "reading",
        description: "ls, cd, cp, mv, rmなど",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "プロセス管理",
        type: "practice",
        description: "ps, top, killコマンド",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-infrastructure-6",
      title: "確認テスト",
      description: "Linuxコマンドの知識",
      type: "choice",
      problem: `実行中のプロセスをリアルタイムで監視し、CPU使用率順に表示するLinuxコマンドはどれですか？`,
      choices: ["top", "ps", "ls", "grep"],
    },
  },
  "infrastructure-7": {
    id: "infrastructure-7",
    title: "負荷分散とスケーリング",
    category: "infrastructure",
    difficulty: "advanced",
    description: "ロードバランサーとオートスケールを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "ロードバランサーの仕組み",
        type: "reading",
        description: "L4/L7分散の違い",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "オートスケーリング",
        type: "practice",
        description: "水平/垂直スケーリング",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-infrastructure-7",
      title: "確認テスト",
      description: "負荷分散の知識",
      type: "text",
      problem: `水平スケーリング（Scale Out）と垂直スケーリング（Scale Up）の違いを説明し、それぞれのメリット・デメリットと適用場面を記述してください。`,
      placeholder: "水平スケーリングはサーバー台数を増やし...、垂直スケーリングはサーバーのスペックを上げて...のように説明してください...",
    },
  },
  "infrastructure-8": {
    id: "infrastructure-8",
    title: "モニタリング設計",
    category: "infrastructure",
    difficulty: "intermediate",
    description: "PrometheusとGrafanaを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "メトリクス収集",
        type: "reading",
        description: "Prometheusの設定",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "可視化ダッシュボード",
        type: "practice",
        description: "Grafanaでのグラフ作成",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-infrastructure-8",
      title: "確認テスト",
      description: "モニタリングの知識",
      type: "choice",
      problem: `Prometheusで収集する時系列データのことを何といいますか？`,
      choices: ["メトリクス（Metrics）", "ログ（Logs）", "トレース（Traces）", "アラート（Alerts）"],
    },
  },
  "infrastructure-9": {
    id: "infrastructure-9",
    title: "ログ管理",
    category: "infrastructure",
    difficulty: "intermediate",
    description: "ELKスタックの構築を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "ログ収集",
        type: "reading",
        description: "Filebeat/Fluentd",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "ログ検索・可視化",
        type: "practice",
        description: "Elasticsearch/Kibana",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-infrastructure-9",
      title: "確認テスト",
      description: "ログ管理の知識",
      type: "text",
      problem: `ELKスタック（Elasticsearch, Logstash, Kibana）でログ収集・解析・可視化を行う際のデータフローを説明してください。各コンポーネントの役割とデータの流れを記述してください。`,
      placeholder: "ログはLogstashで収集・処理され、Elasticsearchに保存され...のように説明してください...",
    },
  },
  "infrastructure-10": {
    id: "infrastructure-10",
    title: "サーバーレスアーキテクチャ",
    category: "infrastructure",
    difficulty: "advanced",
    description: "AWS LambdaとAPI Gatewayを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Lambdaの基礎",
        type: "reading",
        description: "関数の作成とトリガー",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "API Gateway連携",
        type: "practice",
        description: "RESTful APIの構築",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-infrastructure-10",
      title: "確認テスト",
      description: "サーバーレスの知識",
      type: "choice",
      problem: `サーバーレスアーキテクチャの最大の利点は何ですか？`,
      choices: ["インフラ管理が不要で、使った分だけ課金される", "常に最高のパフォーマンスが保証される", "セキュリティの心配が一切ない", "コールドスタート問題が発生しない"],
    },
  },
  "game-3": {
    id: "game-3",
    title: "2Dゲーム開発",
    category: "game",
    difficulty: "intermediate",
    description: "プラットフォーマーゲームの制作を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "2Dスプライト",
        type: "reading",
        description: "画像の表示とアニメーション",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "ジャンプ処理",
        type: "practice",
        description: "物理演算を使った移動",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-game-3",
      title: "確認テスト",
      description: "2Dゲーム開発の知識",
      type: "choice",
      problem: `2Dプラットフォーマーゲームで、キャラクターが地面に接触しているか判定する際に使われる技術は何ですか？`,
      choices: ["コリジョン検出（Collision Detection）", "レイヤーマスキング（Layer Masking）", "レイキャスト（Raycast）", "トリガーコライダー（Trigger Collider）"],
    },
  },
  "game-4": {
    id: "game-4",
    title: "3Dゲーム開発",
    category: "game",
    difficulty: "advanced",
    description: "3D空間のゲーム制作を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "3Dモデル配置",
        type: "reading",
        description: "メッシュとマテリアル",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "カメラ制御",
        type: "practice",
        description: "3人称視点の実装",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-game-4",
      title: "確認テスト",
      description: "3Dゲーム開発の知識",
      type: "text",
      problem: `3Dゲーム開発における「Transform（変換）」の3つの基本要素（Position, Rotation, Scale）がどのように機能し、ゲームオブジェクトの配置・向き・大きさに影響するか説明してください。`,
      placeholder: "Positionは位置座標を...、Rotationは回転角度を...のように説明してください...",
    },
  },
  "game-5": {
    id: "game-5",
    title: "ゲーム物理演算",
    category: "game",
    difficulty: "intermediate",
    description: "物理エンジンの活用を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "Rigidbody",
        type: "reading",
        description: "重力と衝突判定",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "ジョイントとヒンジ",
        type: "practice",
        description: "オブジェクトの連結",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-game-5",
      title: "確認テスト",
      description: "物理演算の知識",
      type: "text",
      problem: `Unityでオブジェクトに重力や物理挙動を付与するために必要なコンポーネントは何ですか？`,
      choices: ["Rigidbody", "Collider", "Transform", "Animator"],
    },
  },
  "game-6": {
    id: "game-6",
    title: "ゲームAI実装",
    category: "game",
    difficulty: "advanced",
    description: "ナビメッシュと敵AIの設計を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "ステートマシン",
        type: "reading",
        description: "AIの状態遷移",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "パスファインディング",
        type: "practice",
        description: "ナビメッシュでの経路探索",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-game-6",
      title: "確認テスト",
      description: "ゲームAIの知識",
      type: "text",
      problem: `ゲームAIで「ビヘイビアツリー（Behavior Tree）」と「ステートマシン（State Machine）」の違いを説明し、それぞれが適している状況を記述してください。`,
      placeholder: "ビヘイビアツリーは階層的な意思決定を...、ステートマシンは状態遷移を...のように説明してください...",
    },
  },
  "game-7": {
    id: "game-7",
    title: "マルチプレイヤー開発",
    category: "game",
    difficulty: "expert",
    description: "ネットワークゲームの実装を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "クライアント・サーバーモデル",
        type: "reading",
        description: "ネットワークアーキテクチャ",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "同期処理",
        type: "practice",
        description: "プレイヤー位置の同期",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-game-7",
      title: "確認テスト",
      description: "マルチプレイヤー開発の知識",
      type: "text",
      problem: `マルチプレイヤーゲームにおける「レイテンシ（遅延）」の問題と、それを緩和するための「クライアント予測（Client Prediction）」と「サーバー調整（Server Reconciliation）」について説明してください。`,
      placeholder: "レイテンシはネットワーク遅延で...、クライアント予測は...のように説明してください...",
    },
  },
  "game-8": {
    id: "game-8",
    title: "モバイルゲーム最適化",
    category: "game",
    difficulty: "intermediate",
    description: "iOS/Android向け最適化を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "パフォーマンス最適化",
        type: "reading",
        description: "ドローコールとバッチング",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "バッテリー消費削減",
        type: "practice",
        description: "フレームレート制御",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-game-8",
      title: "確認テスト",
      description: "モバイルゲーム最適化の知識",
      type: "choice",
      problem: `モバイルゲームでバッテリー消費を抑えるために最も効果的な最適化手法はどれですか？`,
      choices: ["フレームレートの制限とGPU負荷の軽減", "高解像度テクスチャの使用", "常時ネットワーク通信の実行", "複雑な物理演算の追加"],
    },
  },
  "game-9": {
    id: "game-9",
    title: "シェーダー入門",
    category: "game",
    difficulty: "advanced",
    description: "HLSLシェーダープログラミングを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "シェーダーの基礎",
        type: "reading",
        description: "頂点シェーダーとフラグメントシェーダー",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "カスタムシェーダー作成",
        type: "practice",
        description: "グロー効果の実装",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-game-9",
      title: "確認テスト",
      description: "シェーダーの知識",
      type: "choice",
      problem: `頂点シェーダー（Vertex Shader）の主な役割は何ですか？`,
      choices: ["頂点の位置や法線を計算し、変換する", "ピクセルの色を計算する", "ジオメトリを生成する", "テクスチャをロードする"],
    },
  },
  "game-10": {
    id: "game-10",
    title: "Unreal Engine基礎",
    category: "game",
    difficulty: "intermediate",
    description: "UE5のブループリントシステムを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "ブループリントの基礎",
        type: "reading",
        description: "ビジュアルスクリプティング",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "アクターの作成",
        type: "practice",
        description: "カスタムゲームオブジェクト",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-game-10",
      title: "確認テスト",
      description: "Unreal Engineの知識",
      type: "text",
      problem: `Unreal Engineの「ブループリント（Blueprint）」とは何か、またそれがC++コーディングと比較してどのような利点と欠点を持つか説明してください。`,
      placeholder: "ブループリントはビジュアルスクリプティングシステムで...、利点は...、欠点は...のように説明してください...",
    },
  },
  "design-3": {
    id: "design-3",
    title: "デザインシステム構築",
    category: "design",
    difficulty: "intermediate",
    description: "コンポーネントライブラリの設計を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "デザイントークン",
        type: "reading",
        description: "色・タイポグラフィ・余白の定義",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "コンポーネント設計",
        type: "practice",
        description: "再利用可能なUIパーツ",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-design-3",
      title: "確認テスト",
      description: "デザインシステムの知識",
      type: "text",
      problem: `デザインシステムにおける「デザイントークン（Design Tokens）」とは何か、またそれが一貫性のあるUIを実現するためにどのように機能するか説明してください。`,
      placeholder: "デザイントークンは色、スペーシング、フォントなどのデザイン属性を変数として...のように説明してください...",
    },
  },
  "design-4": {
    id: "design-4",
    title: "カラーセオリー",
    category: "design",
    difficulty: "beginner",
    description: "配色の基礎理論を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "色の3属性",
        type: "reading",
        description: "色相・彩度・明度",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "配色パターン",
        type: "practice",
        description: "補色・類似色・三角配色",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-design-4",
      title: "確認テスト",
      description: "カラーセオリーの理解",
      type: "text",
      problem: `色相環で正反対に位置する色を何といいますか？`,
      choices: ["補色（Complementary Color）", "類似色（Analogous Color）", "三色配色（Triadic Color）", "モノクローム（Monochrome）"],
    },
  },
  "design-5": {
    id: "design-5",
    title: "タイポグラフィ",
    category: "design",
    difficulty: "intermediate",
    description: "文字組みとフォント選定を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "フォントの種類",
        type: "reading",
        description: "セリフ・サンセリフ・モノスペース",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "文字組みの原則",
        type: "practice",
        description: "行間・文字間の調整",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-design-5",
      title: "確認テスト",
      description: "タイポグラフィの知識",
      type: "text",
      problem: `タイポグラフィにおける「カーニング（Kerning）」と「トラッキング（Tracking）」の違いを説明し、それぞれどのような場面で使用するか記述してください。`,
      placeholder: "カーニングは特定の文字ペア間の調整で...、トラッキングは全体的な文字間を...のように説明してください...",
    },
  },
  "design-6": {
    id: "design-6",
    title: "プロトタイピング",
    category: "design",
    difficulty: "intermediate",
    description: "インタラクティブなプロトタイプ制作を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "ローファイプロトタイプ",
        type: "reading",
        description: "ワイヤーフレームの作成",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "ハイファイプロトタイプ",
        type: "practice",
        description: "インタラクション設計",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-design-6",
      title: "確認テスト",
      description: "プロトタイピングの知識",
      type: "choice",
      problem: `プロトタイプで、手書きのスケッチや簡単なワイヤーフレームを使った大まかなモデルを何といいますか？`,
      choices: ["ローファイプロトタイプ（Low-fidelity Prototype）", "ハイファイプロトタイプ（High-fidelity Prototype）", "インタラクティブプロトタイプ", "機能プロトタイプ"],
    },
  },
  "design-7": {
    id: "design-7",
    title: "ユーザーリサーチ",
    category: "design",
    difficulty: "intermediate",
    description: "ユーザーインタビューと分析を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "インタビュー手法",
        type: "reading",
        description: "質問の設計と実施",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "ペルソナ作成",
        type: "practice",
        description: "ユーザー像の定義",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-design-7",
      title: "確認テスト",
      description: "ユーザーリサーチの知識",
      type: "text",
      problem: `ユーザーリサーチで「ペルソナ（Persona）」を作成する目的と、またそれがデザイン意思決定にどのように役立つか説明してください。`,
      placeholder: "ペルソナはターゲットユーザーの代表的なモデルで...、共通認識を...のように説明してください...",
    },
  },
  "design-8": {
    id: "design-8",
    title: "レスポンシブデザイン",
    category: "design",
    difficulty: "intermediate",
    description: "デバイス対応のデザイン手法を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "ブレークポイント",
        type: "reading",
        description: "画面サイズごとのレイアウト",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "フルードグリッド",
        type: "practice",
        description: "可変的なレイアウトシステム",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-design-8",
      title: "確認テスト",
      description: "レスポンシブデザインの知識",
      type: "choice",
      problem: `レスポンシブデザインで、スマートフォンの小さな画面から始めてデザインするアプローチを何といいますか？`,
      choices: ["モバイルファースト（Mobile First）", "デスクトップファースト（Desktop First）", "アダプティブデザイン（Adaptive Design）", "フルイドデザイン（Fluid Design）"],
    },
  },
  "design-9": {
    id: "design-9",
    title: "アニメーション設計",
    category: "design",
    difficulty: "advanced",
    description: "モーションデザインの原則を学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "イージング",
        type: "reading",
        description: "自然な動きの表現",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "トランジション設計",
        type: "practice",
        description: "画面遷移のアニメーション",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-design-9",
      title: "確認テスト",
      description: "アニメーション設計の知識",
      type: "text",
      problem: `UIアニメーションで「イージング（Easing）」が重要な理由と、ease-in、ease-out、ease-in-outの違いを説明してください。`,
      placeholder: "イージングはアニメーションの加速・減速を制御し...、ease-inは徐々に始まり...のように説明してください...",
    },
  },
  "design-10": {
    id: "design-10",
    title: "デザイン思考",
    category: "design",
    difficulty: "advanced",
    description: "デザインプロセスとイノベーションを学びます。",
    lessons: [
      {
        id: "lesson-1",
        number: 1,
        title: "デザイン思考のプロセス",
        type: "reading",
        description: "共感・定義・発想・試作・テスト",
        completed: false,
      },
      {
        id: "lesson-2",
        number: 2,
        title: "アイデア発想法",
        type: "practice",
        description: "ブレインストーミングとマインドマップ",
        completed: false,
      },
    ],
    confirmationTest: {
      id: "test-design-10",
      title: "確認テスト",
      description: "デザイン思考の知識",
      type: "text",
      problem: `デザイン思考の5つのステップのうち、「共感（Empathize）」フェーズの目的と、その後の「定義（Define）」フェーズでどのように問題を明確化するか説明してください。`,
      placeholder: "共感フェーズではユーザーを深く理解し...、定義フェーズでは問題を...のように説明してください...",
    },
  },
};

export const getExerciseDetail = async (
  exerciseId: string
): Promise<ExerciseDetail | null> => {
  // 実際のAPIコールをシミュレート
  await new Promise((resolve) => setTimeout(resolve, 300));
  return mockExerciseDetails[exerciseId] || null;
};
