import { Exercise } from '../types';

export const getExercisesByCategory = async (category: string): Promise<Exercise[]> => {
  // TODO: Replace with actual API call
  await new Promise((resolve) => setTimeout(resolve, 300));

  const exercises: Record<string, Exercise[]> = {
    web: [
      {
        id: 'web-html-basics',
        title: 'HTML/CSSの基礎',
        category: 'web',
        difficulty: 'beginner',
        status: 'completed',
        estimatedTime: 30,
        description: 'HTMLとCSSの基本的な使い方を学びます',
        completionRate: 100,
      },
      {
        id: 'web-responsive-design',
        title: 'レスポンシブデザイン入門',
        category: 'web',
        difficulty: 'beginner',
        status: 'in-progress',
        estimatedTime: 45,
        description: 'モバイルフレンドリーなWebサイトの作り方',
        completionRate: 60,
      },
      {
        id: 'web-javascript-basics',
        title: 'JavaScript基礎',
        category: 'web',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 60,
        description: 'JavaScriptの基本文法とDOM操作',
      },
      {
        id: 'web-react-intro',
        title: 'React入門',
        category: 'web',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 90,
        description: 'Reactコンポーネントの作成方法',
      },
      {
        id: 'web-nextjs-app',
        title: 'Next.jsでアプリ開発',
        category: 'web',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 120,
        description: 'Next.jsを使ったフルスタックアプリケーション',
      },
      {
        id: 'web-6',
        title: 'パフォーマンス最適化',
        category: 'web',
        difficulty: 'expert',
        status: 'not-started',
        estimatedTime: 90,
        description: 'Webアプリケーションのパフォーマンス改善手法',
      },
      {
        id: 'web-7',
        title: 'TypeScript基礎',
        category: 'web',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 60,
        description: 'TypeScriptの型システムと基本文法',
      },
      {
        id: 'web-8',
        title: 'Tailwind CSS実践',
        category: 'web',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 45,
        description: 'ユーティリティファーストCSSフレームワーク',
      },
      {
        id: 'web-9',
        title: 'REST API設計',
        category: 'web',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 75,
        description: 'RESTfulなAPI設計の原則',
      },
      {
        id: 'web-10',
        title: 'Git/GitHub実践',
        category: 'web',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 40,
        description: 'バージョン管理とチーム開発',
      },
      {
        id: 'web-11',
        title: 'Webアクセシビリティ',
        category: 'web',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 60,
        description: '誰でも使いやすいWebサイトの作り方',
      },
      {
        id: 'web-12',
        title: 'PWA開発',
        category: 'web',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 90,
        description: 'Progressive Web Appの構築',
      },
    ],
    ai: [
      {
        id: 'ai-1',
        title: '機械学習の基礎',
        category: 'ai',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 60,
        description: '機械学習の基本概念を学びます',
      },
      {
        id: 'ai-2',
        title: 'Python for AI',
        category: 'ai',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 45,
        description: 'AI開発に必要なPythonの基礎',
      },
      {
        id: 'ai-3',
        title: 'ニューラルネットワーク入門',
        category: 'ai',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 90,
        description: 'ニューラルネットワークの仕組み',
      },
      {
        id: 'ai-4',
        title: 'ディープラーニング実践',
        category: 'ai',
        difficulty: 'expert',
        status: 'not-started',
        estimatedTime: 120,
        description: 'CNNとRNNの実装',
      },
      {
        id: 'ai-5',
        title: 'データ前処理',
        category: 'ai',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 40,
        description: 'データクリーニングと正規化',
      },
      {
        id: 'ai-6',
        title: '自然言語処理入門',
        category: 'ai',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 70,
        description: 'NLPの基礎とトークン化',
      },
      {
        id: 'ai-7',
        title: 'コンピュータビジョン',
        category: 'ai',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 90,
        description: '画像認識と物体検出',
      },
      {
        id: 'ai-8',
        title: '強化学習基礎',
        category: 'ai',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 100,
        description: 'Q学習とDQNの実装',
      },
      {
        id: 'ai-9',
        title: 'TensorFlow実践',
        category: 'ai',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 80,
        description: 'TensorFlowでのモデル構築',
      },
      {
        id: 'ai-10',
        title: 'PyTorch入門',
        category: 'ai',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 75,
        description: 'PyTorchの基礎と実装',
      },
      {
        id: 'ai-11',
        title: 'MLOps実践',
        category: 'ai',
        difficulty: 'expert',
        status: 'not-started',
        estimatedTime: 120,
        description: '機械学習モデルのデプロイと運用',
      },    ],
    security: [
      {
        id: 'security-1',
        title: 'セキュリティ基礎',
        category: 'security',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 30,
        description: '情報セキュリティの基本',
      },
      {
        id: 'security-2',
        title: 'Webセキュリティ',
        category: 'security',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 60,
        description: 'XSSやCSRFなどの脆弱性対策',
      },
      {
        id: 'security-3',
        title: 'ペネトレーションテスト',
        category: 'security',
        difficulty: 'expert',
        status: 'not-started',
        estimatedTime: 120,
        description: 'セキュリティ診断と脆弱性評価',
      },
      {
        id: 'security-4',
        title: '暗号化技術',
        category: 'security',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 60,
        description: '対称暗号と公開鍵暗号',
      },
      {
        id: 'security-5',
        title: 'OAuth/JWT認証',
        category: 'security',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 70,
        description: 'モダン認証の実装',
      },
      {
        id: 'security-6',
        title: 'OWASP Top 10',
        category: 'security',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 50,
        description: '代表的なWeb脆弱性',
      },
      {
        id: 'security-7',
        title: 'セキュアコーディング',
        category: 'security',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 80,
        description: '安全なコードの書き方',
      },
      {
        id: 'security-8',
        title: 'ネットワークセキュリティ',
        category: 'security',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 90,
        description: 'ファイアウォールとIDS/IPS',
      },
      {
        id: 'security-9',
        title: 'インシデント対応',
        category: 'security',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 100,
        description: 'セキュリティ事故への対処',
      },
      {
        id: 'security-10',
        title: 'クラウドセキュリティ',
        category: 'security',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 85,
        description: 'AWS/Azureのセキュリティ対策',
      },
    ],
    infrastructure: [
      {
        id: 'infrastructure-1',
        title: 'Docker基礎',
        category: 'infrastructure',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 50,
        description: 'コンテナ技術の基礎',
      },
      {
        id: 'infrastructure-2',
        title: 'Kubernetes入門',
        category: 'infrastructure',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 90,
        description: 'コンテナオーケストレーション',
      },
      {
        id: 'infrastructure-3',
        title: 'CI/CD構築',
        category: 'infrastructure',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 80,
        description: 'GitHub ActionsとJenkins',
      },
      {
        id: 'infrastructure-4',
        title: 'AWS基礎',
        category: 'infrastructure',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 60,
        description: 'EC2, S3, RDSの基本',
      },
      {
        id: 'infrastructure-5',
        title: 'Terraform実践',
        category: 'infrastructure',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 100,
        description: 'Infrastructure as Code',
      },
      {
        id: 'infrastructure-6',
        title: 'Linuxサーバー管理',
        category: 'infrastructure',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 70,
        description: 'シェルコマンドとシステム管理',
      },
      {
        id: 'infrastructure-7',
        title: '負荷分散とスケーリング',
        category: 'infrastructure',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 90,
        description: 'ロードバランサーとオートスケール',
      },
      {
        id: 'infrastructure-8',
        title: 'モニタリング設計',
        category: 'infrastructure',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 75,
        description: 'PrometheusとGrafana',
      },
      {
        id: 'infrastructure-9',
        title: 'ログ管理',
        category: 'infrastructure',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 65,
        description: 'ELKスタックの構築',
      },
      {
        id: 'infrastructure-10',
        title: 'サーバーレスアーキテクチャ',
        category: 'infrastructure',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 85,
        description: 'AWS LambdaとAPI Gateway',
      },
    ],
    game: [
      {
        id: 'game-1',
        title: 'Unity基礎',
        category: 'game',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 60,
        description: 'Unityエンジンの基本操作',
      },
      {
        id: 'game-2',
        title: 'C#ゲームプログラミング',
        category: 'game',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 70,
        description: 'UnityでのC#スクリプティング',
      },
      {
        id: 'game-3',
        title: '2Dゲーム開発',
        category: 'game',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 90,
        description: 'プラットフォーマーゲームの制作',
      },
      {
        id: 'game-4',
        title: '3Dゲーム開発',
        category: 'game',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 120,
        description: '3D空間のゲーム制作',
      },
      {
        id: 'game-5',
        title: 'ゲーム物理演算',
        category: 'game',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 75,
        description: '物理エンジンの活用',
      },
      {
        id: 'game-6',
        title: 'ゲームAI実装',
        category: 'game',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 100,
        description: 'ナビメッシュと敵AIの設計',
      },
      {
        id: 'game-7',
        title: 'マルチプレイヤー開発',
        category: 'game',
        difficulty: 'expert',
        status: 'not-started',
        estimatedTime: 150,
        description: 'ネットワークゲームの実装',
      },
      {
        id: 'game-8',
        title: 'モバイルゲーム最適化',
        category: 'game',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 80,
        description: 'iOS/Android向け最適化',
      },
      {
        id: 'game-9',
        title: 'シェーダー入門',
        category: 'game',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 95,
        description: 'HLSLシェーダープログラミング',
      },
      {
        id: 'game-10',
        title: 'Unreal Engine基礎',
        category: 'game',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 85,
        description: 'UE5のブループリントシステム',
      },
    ],
    design: [
      {
        id: 'design-1',
        title: 'UI/UX基礎',
        category: 'design',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 45,
        description: 'ユーザーインターフェース設計の原則',
      },
      {
        id: 'design-2',
        title: 'Figma実践',
        category: 'design',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 55,
        description: 'Figmaでのデザイン制作',
      },
      {
        id: 'design-3',
        title: 'デザインシステム構築',
        category: 'design',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 80,
        description: 'コンポーネントライブラリの設計',
      },
      {
        id: 'design-4',
        title: 'カラーセオリー',
        category: 'design',
        difficulty: 'beginner',
        status: 'not-started',
        estimatedTime: 40,
        description: '配色の基礎理論',
      },
      {
        id: 'design-5',
        title: 'タイポグラフィ',
        category: 'design',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 50,
        description: '文字組みとフォント選定',
      },
      {
        id: 'design-6',
        title: 'プロトタイピング',
        category: 'design',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 70,
        description: 'インタラクティブなプロトタイプ制作',
      },
      {
        id: 'design-7',
        title: 'ユーザーリサーチ',
        category: 'design',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 65,
        description: 'ユーザーインタビューと分析',
      },
      {
        id: 'design-8',
        title: 'レスポンシブデザイン',
        category: 'design',
        difficulty: 'intermediate',
        status: 'not-started',
        estimatedTime: 60,
        description: 'デバイス対応のデザイン手法',
      },
      {
        id: 'design-9',
        title: 'アニメーション設計',
        category: 'design',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 85,
        description: 'モーションデザインの原則',
      },
      {
        id: 'design-10',
        title: 'デザイン思考',
        category: 'design',
        difficulty: 'advanced',
        status: 'not-started',
        estimatedTime: 90,
        description: 'デザインプロセスとイノベーション',
      },
    ],
  };

  const categoryKey = category.toLowerCase();
  return exercises[categoryKey] || [];
};
