export type NodeStatus = "completed" | "available" | "locked"
export type SkillCategory = "none" | "web" | "ai" | "security" | "infra" | "design" | "game" | "mixed"

export interface SkillNode {
  id: string
  label: string
  category: SkillCategory
  status: NodeStatus
  x: number
  y: number
  tier: number
  description: string
  children: string[]
  requiredPoints: number
  requiredPointsMap?: Partial<Record<SkillCategory, number>> // for mixed nodes
}

export interface RankInfo {
  tier: number
  nameJa: string
  nameEn: string
  level: "beginner" | "intermediate" | "master"
}

export const RANKS: RankInfo[] = [
  { tier: 1, nameJa: "種子", nameEn: "Seed", level: "beginner" },
  { tier: 2, nameJa: "苗木", nameEn: "Sprout", level: "beginner" },
  { tier: 3, nameJa: "若木", nameEn: "Sapling", level: "beginner" },
  { tier: 4, nameJa: "巨木", nameEn: "Giant Tree", level: "intermediate" },
  { tier: 5, nameJa: "母樹", nameEn: "Mother Tree", level: "intermediate" },
  { tier: 6, nameJa: "林", nameEn: "Grove", level: "intermediate" },
  { tier: 7, nameJa: "森", nameEn: "Forest", level: "intermediate" },
  { tier: 8, nameJa: "霊樹", nameEn: "Spirit Tree", level: "master" },
  { tier: 9, nameJa: "古樹", nameEn: "Ancient Tree", level: "master" },
  { tier: 10, nameJa: "世界樹", nameEn: "World Tree", level: "master" },
]

const X = {
  infra: -1250,
  security: -750,
  ai: -250,
  web: 250,
  design: 750,
  game: 1250,
}

export const SKILL_NODES: SkillNode[] = [
  {
    id: "egg",
    label: "エンジニアの卵",
    category: "none",
    status: "completed",
    x: 0, y: 500,
    tier: 0,
    description: "すべてのエンジニアの出発点。ここから技術の旅が始まる。",
    children: ["infra-1", "security-1", "ai-1", "web-1", "design-1", "game-1"],
    requiredPoints: 0,
  },
  // --- Infra ---
  {
    id: "infra-1",
    label: "インフラ入門",
    category: "infra",
    status: "available",
    x: X.infra, y: 250,
    tier: 1,
    description: "Linux・ネットワーク・サーバーの基礎。すべての土台となる知識。",
    children: ["infra-2"],
    requiredPoints: 1,
  },
  {
    id: "infra-2",
    label: "コンテナ＆クラウド",
    category: "infra",
    status: "locked",
    x: X.infra, y: 50,
    tier: 2,
    description: "Dockerの基本概念と主要クラウドサービスの基礎。",
    children: ["infra-3"],
    requiredPoints: 2,
  },
  {
    id: "infra-3",
    label: "Kubernetes",
    category: "infra",
    status: "locked",
    x: X.infra, y: -150,
    tier: 3,
    description: "Kubernetesクラスター管理とオーケストレーション。",
    children: ["infra-4"],
    requiredPoints: 3,
  },
  {
    id: "infra-4",
    label: "SREエンジニア",
    category: "infra",
    status: "locked",
    x: X.infra, y: -380,
    tier: 4,
    description: "信頼性エンジニアリング・SLO設計・インシデント対応。",
    children: ["mixed-infra-sec"],
    requiredPoints: 4,
  },

  // --- Security ---
  {
    id: "security-1",
    label: "セキュリティ入門",
    category: "security",
    status: "available",
    x: X.security, y: 250,
    tier: 1,
    description: "情報セキュリティの基本と脅威モデルを理解する。",
    children: ["security-2"],
    requiredPoints: 1,
  },
  {
    id: "security-2",
    label: "Web＆ネットワーク防御",
    category: "security",
    status: "locked",
    x: X.security, y: 50,
    tier: 2,
    description: "主要なWeb攻撃と防御、およびネットワークの保護手法。",
    children: ["security-3"],
    requiredPoints: 2,
  },
  {
    id: "security-3",
    label: "ペネトレーション",
    category: "security",
    status: "locked",
    x: X.security, y: -150,
    tier: 3,
    description: "脆弱性診断とペネトレーションテスト手法。",
    children: ["security-4"],
    requiredPoints: 3,
  },
  {
    id: "security-4",
    label: "セキュリティ設計",
    category: "security",
    status: "locked",
    x: X.security, y: -380,
    tier: 4,
    description: "ゼロトラスト・脅威モデリング・セキュリティアーキテクチャ。",
    children: ["mixed-infra-sec", "mixed-sec-ai"],
    requiredPoints: 4,
  },

  // --- AI ---
  {
    id: "ai-1",
    label: "AI/ML入門",
    category: "ai",
    status: "available",
    x: X.ai, y: 250,
    tier: 1,
    description: "機械学習の基本概念とPythonデータサイエンスの入門。",
    children: ["ai-2"],
    requiredPoints: 1,
  },
  {
    id: "ai-2",
    label: "機械学習応用＆LLM",
    category: "ai",
    status: "locked",
    x: X.ai, y: 50,
    tier: 2,
    description: "教師あり/なし学習の中級スキルと大規模言語モデルの基礎。",
    children: ["ai-3"],
    requiredPoints: 2,
  },
  {
    id: "ai-3",
    label: "深層学習",
    category: "ai",
    status: "locked",
    x: X.ai, y: -150,
    tier: 3,
    description: "CNN・RNN・TransformerアーキテクチャとLLMアプリ構築。",
    children: ["ai-4"],
    requiredPoints: 3,
  },
  {
    id: "ai-4",
    label: "AIエンジニアリング",
    category: "ai",
    status: "locked",
    x: X.ai, y: -380,
    tier: 4,
    description: "AI/MLシステムの設計から本番運用まで。MLOps実践。",
    children: ["mixed-sec-ai", "mixed-ai-web"],
    requiredPoints: 4,
  },

  // --- Web ---
  {
    id: "web-1",
    label: "Web入門",
    category: "web",
    status: "available",
    x: X.web, y: 250,
    tier: 1,
    description: "HTML/CSS/JavaScriptを理解し、Webの仕組みを学ぶ。",
    children: ["web-2"],
    requiredPoints: 1,
  },
  {
    id: "web-2",
    label: "フルスタック基礎",
    category: "web",
    status: "locked",
    x: X.web, y: 50,
    tier: 2,
    description: "React等のモダンフロントエンド開発とNode.js等のバックエンド基礎。",
    children: ["web-3"],
    requiredPoints: 2,
  },
  {
    id: "web-3",
    label: "フルスタック応用",
    category: "web",
    status: "locked",
    x: X.web, y: -150,
    tier: 3,
    description: "フロント/バック/DBを統合した高度な開発力を身につける。",
    children: ["web-4"],
    requiredPoints: 3,
  },
  {
    id: "web-4",
    label: "テックリード",
    category: "web",
    status: "locked",
    x: X.web, y: -380,
    tier: 4,
    description: "チームを技術的にリードし、アーキテクチャを設計する。",
    children: ["mixed-ai-web", "mixed-web-design"],
    requiredPoints: 4,
  },

  // --- Design ---
  {
    id: "design-1",
    label: "デザイン入門",
    category: "design",
    status: "available",
    x: X.design, y: 250,
    tier: 1,
    description: "UI/UXデザインの基本原則とデザインツールを習得する。",
    children: ["design-2"],
    requiredPoints: 1,
  },
  {
    id: "design-2",
    label: "UI設計＆体験検証",
    category: "design",
    status: "locked",
    x: X.design, y: 50,
    tier: 2,
    description: "Figmaを用いたUIコンポーネント設計とユーザー検証手法。",
    children: ["design-3"],
    requiredPoints: 2,
  },
  {
    id: "design-3",
    label: "デザインシステム",
    category: "design",
    status: "locked",
    x: X.design, y: -150,
    tier: 3,
    description: "スケーラブルなデザインシステムの構築と運用。",
    children: ["design-4"],
    requiredPoints: 3,
  },
  {
    id: "design-4",
    label: "クリエイティブ技術",
    category: "design",
    status: "locked",
    x: X.design, y: -380,
    tier: 4,
    description: "3D・アニメーション・インタラクティブアートを統合する。",
    children: ["mixed-web-design", "mixed-design-game"],
    requiredPoints: 4,
  },

  // --- Game ---
  {
    id: "game-1",
    label: "ゲーム開発入門",
    category: "game",
    status: "available",
    x: X.game, y: 250,
    tier: 1,
    description: "ゲームエンジンと基本的なゲーム開発の概念を学ぶ。",
    children: ["game-2"],
    requiredPoints: 1,
  },
  {
    id: "game-2",
    label: "ゲーム設計＆エンジン",
    category: "game",
    status: "locked",
    x: X.game, y: 50,
    tier: 2,
    description: "ゲームエンジンの基本操作とゲームメカニクス基礎。",
    children: ["game-3"],
    requiredPoints: 2,
  },
  {
    id: "game-3",
    label: "ゲームプログラミング",
    category: "game",
    status: "locked",
    x: X.game, y: -150,
    tier: 3,
    description: "物理演算・シェーダー・最適化を駆使した高度な開発。",
    children: ["game-4"],
    requiredPoints: 3,
  },
  {
    id: "game-4",
    label: "ゲームディレクター",
    category: "game",
    status: "locked",
    x: X.game, y: -380,
    tier: 4,
    description: "ゲーム全体の設計・開発・ローンチを主導する。",
    children: ["mixed-design-game"],
    requiredPoints: 4,
  },

  // === Mixed Nodes ===
  {
    id: "mixed-infra-sec",
    label: "DevSecOps",
    category: "mixed",
    status: "locked",
    x: -1000, y: -500,
    tier: 5,
    description: "インフラとセキュリティの高度な融合。",
    children: [],
    requiredPoints: 0,
    requiredPointsMap: { infra: 4, security: 4 },
  },
  {
    id: "mixed-sec-ai",
    label: "AIセキュリティ",
    category: "mixed",
    status: "locked",
    x: -500, y: -500,
    tier: 5,
    description: "AIシステムの脆弱性防御とセキュアなモデル運用。",
    children: [],
    requiredPoints: 0,
    requiredPointsMap: { security: 4, ai: 4 },
  },
  {
    id: "mixed-ai-web",
    label: "AI駆動Webアプリ",
    category: "mixed",
    status: "locked",
    x: 0, y: -500,
    tier: 5,
    description: "次世代のAI統合Webサービス開発。",
    children: [],
    requiredPoints: 0,
    requiredPointsMap: { ai: 4, web: 4 },
  },
  {
    id: "mixed-web-design",
    label: "UXエンジニア",
    category: "mixed",
    status: "locked",
    x: 500, y: -500,
    tier: 5,
    description: "最高峰のユーザー体験を実装する専門家。",
    children: [],
    requiredPoints: 0,
    requiredPointsMap: { web: 4, design: 4 },
  },
  {
    id: "mixed-design-game",
    label: "テクニカルアート",
    category: "mixed",
    status: "locked",
    x: 1000, y: -500,
    tier: 5,
    description: "デザインとゲームエンジンの境地。",
    children: [],
    requiredPoints: 0,
    requiredPointsMap: { design: 4, game: 4 },
  },
]

export function getNodeById(id: string): SkillNode | undefined {
  return SKILL_NODES.find((n) => n.id === id)
}
